### ISSUE TITLE
希望增加文件夹的需求

### ISSUE THREAD

**Issue by sunu11** [coolerwu/FireFire#26]
使用了一下，创建笔记感觉还好，但是无法创建文件夹，希望大佬增加这个需求呀，比如1月，1日、2日、3日之类的

**Comment by coolerwu** [comment]
> 使用了一下，创建笔记感觉还好，但是无法创建文件夹，希望大佬增加这个需求呀，比如1月，1日、2日、3日之类的

正在研发中，应该很快就能上了

**Comment by sunu11** [comment]
您好  您的邮件已收到。稍后给您回复。

**Comment by sunu11** [comment]
您好  您的邮件已收到。稍后给您回复。
